# Generated by Django 5.0.6 on 2024-06-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employee_Details',
        ),
    ]
