# Generated by Django 5.0.6 on 2024-07-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_employee_employee_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='Picture',
            field=models.ImageField(default=1, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
