# Generated by Django 5.0.6 on 2024-07-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_details_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='Picture',
        ),
    ]
